### ISSUE TITLE
Undefined variable in 1.2.6

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#19]
Hi

Im getting these msg in the error log after upgrading to 1.2.6 when entering the module admin.
`2019-10-03 17:56:20 - PHP Notice:  Undefined variable: payment_bambora_online_checkout_payment_method_update in /public_html/admin/view/template/extension/payment/bambora_online_checkout.tpl on line 194
2019-10-03 17:56:20 - PHP Notice:  Undefined variable: text_yes in /public_html/admin/view/template/extension/payment/bambora_online_checkout.tpl on line 201
2019-10-03 17:56:20 - PHP Notice:  Undefined variable: text_no in /public_html/admin/view/template/extension/payment/bambora_online_checkout.tpl on line 202`

**Comment by ReodorFelgen** [comment]
Adding this:
`            //Common
            'text_yes',
            'text_no',`

After "'help_sort_order'," on line 113 in the file "admin/controller/extension/payment/bambora_online_checkout.php" fixes that error. 

Also to make it save your settings change line 192 in the file "admin/view/template/extension/payment/bambora_online_checkout.tpl" to this:

`<select name="bambora_online_checkout_payment_method_update" id="input-payment-method-update" class="form-control">`

And change line 194 to this:
`<?php if (isset($bambora_online_checkout_payment_method_update) && $bambora_online_checkout_payment_method_update == '1') { ?>`

**Comment by sessan** [comment]
This issue is fixed in the 1.4.1 version. Thanks for pointing it out!

Best Regards
Jessica, Bambora Online

**Comment by syntaxerror** [comment]
Hi there @sessan,

Seems like you missed a part of it for OC2.3, mentioned by @ReodorFelgen above, who also was in my ignored patch here: https://github.com/syntaxerror/bambora-checkout-opencart-v2.3plus/commit/f990524685616b8faf01e27f6ae1eaa2625ae384

Remember that OC3 and OC2.3 doesn't work 100% the same, so it's important to check both, or drop support for OC2.3 (which isn't recommended anyway).

Also remember to keep the tpl (OC2.3) and twig (OC3) files in sync, as they are not now, and I have commented your code on this a few places/times (ignored).
